<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="vipul" failures="1" tests="1" name="testcase(failed)(failed)" time="21.444" errors="0" timestamp="2019-12-09T17:16:54 IST">
  <testcase classname="com.stock.qa.testcases.AddProductCategoryTest" name="verify_Addproductcategory_Test" time="12.548">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.stock.qa.testcases.AddProductCategoryTest.verify_Addproductcategory_Test(AddProductCategoryTest.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- verify_Addproductcategory_Test -->
  <testcase classname="com.stock.qa.testcases.AddProductCategoryTest" name="verify_Settings_Test" time="0.0">
    <ignored/>
  </testcase> <!-- verify_Settings_Test -->
  <testcase classname="com.stock.qa.testcases.AddProductCategoryTest" name="verify_Addproduct_Category_TitleNameTest" time="0.0">
    <ignored/>
  </testcase> <!-- verify_Addproduct_Category_TitleNameTest -->
</testsuite> <!-- testcase(failed)(failed) -->
